/* Header for module boxglobl, generated by p2c */
#ifndef BOXGLOBL_H
#define BOXGLOBL_H


#ifndef PASTRIX_H
#include "pastrix.h"
#endif

#ifndef DPGLOBAL_H
#include "dpglobal.h"
#endif


#ifdef BOXGLOBL_G
# define vextern
#else
# define vextern extern
#endif


/* Konstanten fÅr umode */

#define UM_USER         0
#define UM_SF_OUT       1
#define UM_TELLREQ      2
#define UM_SYSREQ       3
#define UM_MODEM_OUT    4
#define UM_MODEM_IN     5


/* Konstanten fÅr sfinpmode (user-sf-login) */

#define SFI_NONE        0
#define SFI_FROMP       1
#define SFI_FROMPB      2
#define SFI_ALL         3


typedef Char msgidmem[13];

typedef Char mbxtype[41];

typedef Char calltype[7];

typedef Char boardtype[9];


typedef struct hboxtyp {
  calltype call;
  mbxtype hpath;
  calltype bestfrom, rxfrom;
  Char desc[41];
  long lasttx, msgct, best, aver, bytect, at;
} hboxtyp;


typedef void (*boxproc1type)(Char *s);

typedef void (*boxproc2type)(short i);

typedef void (*boxproc0type)(void);

typedef void (*boxproc3type)(short i, Char *s);

typedef void (*boxproc5type)(short i, Char *s, boolean b);

typedef void (*boxproc6type)(short i, short t);

typedef void (*boxproc7type)(short i, boolean b);

typedef void (*boxproc8type)
(short i, Char *s1, Char *s2, boolean b1, boolean b2, boolean b3);

typedef void (*boxproc9type)
(boolean b, Char *s1, short i, short k, long l1, long l2, long l3, Char *s2);

typedef void (*boxproc10type)(long l);

typedef void (*boxproc11type)(Char *s, boolean b);

typedef void (*boxproc12type)
(Char *s, uchar *p, long l1, long l2, boolean b1, boolean b2, boolean b3);

typedef void (*boxproc13type)(short i, boolean b, Char *s);

typedef void (*boxproc14type)(Char *s, uchar **p, long *l, long k);

typedef void (*boxproc15type)(Char *s);

typedef void (*boxproc16type)(Char *s);

typedef void (*boxproc17type)(short i1, short i2, short i3);

typedef void (*boxproc18type)
(short i1, short i2, short i3, boolean b, uchar *p, long l);

typedef void (*boxproc19type)
(short i1, short i2, short i3, Char *s, boolean b);

typedef void (*boxproc20type)(short i, Char *s);

typedef void (*boxproc21type)(short i, Char *s, boolean b);

typedef void (*boxproc22type)(short i, Char *s);

typedef void (*boxproc23type)(short i, Char *s);

typedef void (*boxproc24type)(boolean b);


typedef unsigned short (*boxfunc3type)(short x);

typedef short (*boxfunc2type)(short x);

typedef short (*boxfunc1type)(void);

typedef boolean (*boxfunc0type)(void);

typedef long (*boxfunc4type)(void);

typedef long (*boxfunc5type)(short i);

typedef boolean (*boxfunc6type)(short i, Char *s1, Char *s2);

typedef unsigned short (*boxfunc7type)(void);

typedef boolean (*boxfunc8type)(short x);

typedef short (*boxfunc9type)(Char *s1, Char *s2);

typedef boolean (*boxfunc10type)(Char *s1, Char *s2, Char *s3);

typedef boolean (*boxfunc11type)(boolean b);

typedef long (*boxfunc12type)(short i1, short i2, short i3);

typedef void (*boxgetstatustype)(boolean sysop, uchar **p, long *sz);

typedef void (*boxfreestatptype)(uchar **p);



extern void boxpushmonstat(short tnc);
extern void boxpopmonstat(short tnc);
extern void boxpushunproto(short tnc);
extern void boxpopunproto(short tnc);
extern void boxsendallbufs(void);
extern void boxloadgreeting(void);
extern void boxsetamouse(void);
extern void boxsetbmouse(void);
extern void boxsetcompwait(short chan, short v);
extern void boxreadallbuffers(void);
extern void boxsaveallbuffers(void);
extern void boxzeichenwandlung(short i, Char *s);
extern short boxmodemport(void);
extern long boxaktqrg(void);
extern long boxtncqrg(short i);
extern short boxboxssid(void);
extern short boxnodessid(void);
extern void boxsetbox(short i, short t);
extern void boxsetwasbox(short i, short t);
extern void boxsetnode(short i, boolean b);
extern void boxstartconnect(short i, Char *s1, Char *s2, boolean b1,
			    boolean b2, boolean b3);
extern short boxcallgemprg(Char *s1, Char *s2);
extern void boxsgdial1(void);
extern void boxegdial1(void);
extern void boxsgdial(void);
extern void boxegdial(void);
extern void boxwait(long l);
extern void boxrgdial1(Char *s);
extern void boxendbusy(void);
extern void boxprprefix(short i, boolean b, Char *s);
extern unsigned short boxruntime(void);
extern void boxfreemostram(boolean b);
extern void boxstartedit(Char *s, uchar *p, long l1, long l2, boolean b1,
			 boolean b2, boolean b3);
extern void boxedit(Char *s, uchar **p, long *l, long k);
extern void boxcancelmultibox(void);
extern void boxprreset(Char *s);
extern void boxprkill(short i, Char *s);
extern void boxprdir(short i, Char *s);
extern boolean boxinitmodem(boolean b);
extern boolean boxexitmodem(boolean b);
extern void boxendmodem(void);
extern void boxspoolfend(short chan);


vextern boxproc7type boxsetboxsf;
vextern boxproc23type boxprwprg2;
vextern boxgetstatustype boxgetstatus;
vextern boxfreestatptype boxfreestatp;
vextern boxproc16type boxprotokoll;
vextern boxproc2type boxendbox, boxpacketendbox;
vextern boxfunc2type boxunackframes;
vextern boxfunc1type boxtnccount;
vextern boxproc20type boxsetunproto;
vextern boxproc21type boxsendpline;
vextern boxfunc0type boxgbstop;
vextern boxfunc2type boxgettncmonchan;
vextern boxproc20type boxsetmonstat, boxsetunattmode;
vextern boxfunc3type boxgetpaclen;
vextern boxproc6type boxsetrwmode;
vextern boxproc7type boxsetboxbin, boxpabortsf;
vextern boxfunc6type boxpboxsf;
vextern boxproc2type boxprdisc;
vextern boxfunc8type boxgetcompmode;
vextern boxproc7type boxsetcompmode;
vextern boxproc9type boxsetgdial;
vextern boxfunc0type boxhoststarted;
vextern boxproc0type boxcheckdiskspace;
vextern boxproc11type boxalert2;
vextern boxproc1type boxbusy;
vextern boxfunc10type boxgetfilename;
vextern boxfunc12type boxspoolstatus;
vextern boxproc17type boxspoolabort;
vextern boxproc18type boxmemspool;
vextern boxproc0type boxspoolread;
vextern boxproc19type boxspool;
vextern boxproc22type boxsetinpfile;

vextern boolean ana_hpath;
vextern uchar left_margin, right_margin;
vextern boolean with_rline, box_pw;
vextern unsigned short sfinpdefault;
vextern boolean bcastforward, multiprivate, send_bbsbcast, user_moncut,
		bulletin_moncut;
vextern unsigned short erasedelay;
vextern boolean auto_garbage, auto_block, remote_erase, mail_beacon,
		packed_sf, hold_view;
vextern long maxbullids, bullidseek;
vextern unsigned short garbagetime, userlifetime, packdelay;

vextern mbxtype ownhiername;
vextern Char ownfheader[31];
vextern Char fbb314_fromfield[21], fbb_fromfield[21], fbb314_tofield[21],
	     fbb_tofield[21];

vextern Char b_eralog[256], u_eralog[256], mybbs_box[256], hpath_box[256],
	     config_box[256], boxrundir[256], boxlanguagedir[256],
	     boxstatdir[256], boxprotodir[256], boxsfdir[256],
	     badnames_box[256], transfer_box[256], autobox_dir[256],
	     bcast_box[256], beacon_box[256], commands_box[256],
	     ctext_box[256], debug_box[256], f6fbb_box[256], modem_box[256],
	     rubriken_box[256], bidseekfile[256], tcpip_box[256],
	     r_erase_box[256], profile_box[256], m_filter_prg[256],
	     resume_inf[256], dp_prg[256], dp_new_prg[256];

vextern Char newmaildir[256], serverdir[256], infodir[256], indexdir[256],
	     boxsysdir[256], u_boxlog[256], msgidlog[256], b_boxlog[256];


#undef vextern

#endif /*BOXGLOBL_H*/

/* End. */
