/* Header for module bcast, generated by p2c */
#ifndef BCAST_H
#define BCAST_H


#ifndef PASTRIX_H
#include "pastrix.h"
#endif

#ifndef DPGLOBAL_H
#include "dpglobal.h"
#endif

#ifndef BOXGLOBL_H
#include "boxglobl.h"
#endif


#ifdef BCAST_G
# define vextern
#else
# define vextern extern
#endif


/*  calltype            =   string[6];
    boardtype           =   string[8];
    msgidmem            =   string[12];
*/
typedef void (*bccbtype)(short chan, short free);


typedef void (*bcastprotokolltype)(Char *s);

typedef void (*bcastsetpidtype)(short x, short y);

typedef void (*bcastsetmonstattype)(short x, Char *s);

typedef void (*bcastsetunprototype)(short x, Char *s);

typedef void (*bcastsendtype)(short x, short y, uchar *p);

typedef void (*bcasttncbuffertype)(bccbtype callback, short x);

typedef short (*bcastmonchantype)(short x);

typedef Char *(*bcastgetmycalltype)(Char *Result, short x);

typedef boolean (*bcastshpacsattype)(void);

typedef Char *(*bcastgetdirtype)(Char *Result);

typedef void (*bcastcreatestatustype)
(boolean b, Char *s1, Char *s2, long t1, long t2, long l, Char c, Char *s3);

typedef void (*bcastsortnewmailtype)(short i, Char *s1, Char *s2);

typedef short (*bcasthuffpackertype)
(boolean b, Char *s1, Char *s2, boolean b1);

typedef boolean (*bcastcheckbidtype)(Char *s);

typedef boolean (*bcastbadnametype)(Char *s);

typedef void (*bcastcallbacktype)(long l);

typedef void (*bcptype)(short x);

typedef void (*bcswitchtype)(short x, boolean y);


vextern bcswitchtype bcastswitchtobc;
vextern bcptype bcastpoppid, bcastpushpid, bcastpopmonstat, bcastpushmonstat,
		bcastpopunproto, bcastpushunproto;

vextern bcastshpacsattype bcastusereingabe;
vextern bcastprotokolltype bcastprotokollcall;
vextern bcastsetpidtype bcastsetpid;
vextern bcastsetmonstattype bcastsetmonstat;
vextern bcastsetunprototype bcastsetunproto;
vextern bcastsendtype bcastsend;
vextern bcasttncbuffertype bcasttncbuffer;
vextern bcastmonchantype bcastmonchan;
vextern bcastgetmycalltype bcastgetmycall;
vextern bcastshpacsattype bcastshpacsat, bcastcreaterequests;
vextern bcastcreatestatustype bcastcreatestatus;
vextern bcastsortnewmailtype bcastsortnewmail;
vextern bcasthuffpackertype bcasthuffpacker;
vextern bcastcheckbidtype bcastcheckbid;
/*  bcastbadname        :   bcastbadnametype; */

vextern bcastgetdirtype BcastTempDir, BcastSaveDir, BcastNewMailDir;


extern boolean bcast_file(uchar stnc, uchar sport, Char *qrg, long fid,
  unsigned short ftype, Char *name1, Char *adress, Char *bbs_source,
  Char *bbs_destination, Char *bbs_ax25uploader, long bbs_upload_time,
  long bbs_expire_time, uchar bbs_compression, Char *bbs_bid,
  Char bbs_msgtype, Char *bbs_title, Char *bbs_fheader,
  unsigned short bodychecksum, boolean delete_after_tx,
  bcastcallbacktype *callbackproc);

extern void bcast_timing(void);
extern boolean dec_bcast(uchar pid, uchar rxtnc, Char *call1, Char *call2,
			 Char *digipeat, unsigned short infosize,
			 uchar *inf1);
extern unsigned short decode_frameheader(uchar *inf1, unsigned short size,
					 Char *sr);
extern void bcast_exit(void);


#undef vextern

#endif /*BCAST_H*/

/* End. */
